name:                 immutable-towers
version:              0.0.0.0
visibility:           public
id:                   immutable-towers-0.0.0.0-inplace
key:                  immutable-towers-0.0.0.0-inplace
author:
    José Manuel Peixoto Rocha <a106887@alunos.uminho.pt>
    David Jose Barbosa Alves <a107324@alunos.uminho.pt>

category:             Game
abi:                  inplace
exposed:              True
exposed-modules:      LI12425 Tarefa1 Tarefa2 Tarefa3
import-dirs:
    /Users/davidalves/Desktop/segundo/LI1/2024li1g017/dist-newstyle/build/aarch64-osx/ghc-9.4.8/immutable-towers-0.0.0.0/build

library-dirs:
    /Users/davidalves/Desktop/segundo/LI1/2024li1g017/dist-newstyle/build/aarch64-osx/ghc-9.4.8/immutable-towers-0.0.0.0/build

dynamic-library-dirs:
    /Users/davidalves/Desktop/segundo/LI1/2024li1g017/dist-newstyle/build/aarch64-osx/ghc-9.4.8/immutable-towers-0.0.0.0/build

data-dir:             /Users/davidalves/Desktop/segundo/LI1/2024li1g017/.
hs-libraries:         HSimmutable-towers-0.0.0.0-inplace
depends:              base-4.17.2.1 rndm-1.2.1.2-723e484d
haddock-interfaces:
    /Users/davidalves/Desktop/segundo/LI1/2024li1g017/dist-newstyle/build/aarch64-osx/ghc-9.4.8/immutable-towers-0.0.0.0/doc/html/immutable-towers/immutable-towers.haddock

haddock-html:
    /Users/davidalves/Desktop/segundo/LI1/2024li1g017/dist-newstyle/build/aarch64-osx/ghc-9.4.8/immutable-towers-0.0.0.0/doc/html/immutable-towers
