name:                 immutable-towers
version:              0.0.0.0
visibility:           public
id:                   immutable-towers-0.0.0.0-inplace
key:                  immutable-towers-0.0.0.0-inplace
author:
    José Manuel Peixoto Rocha <a106887@alunos.uminho.pt>
    David Jose Barbosa Alves <a107324@alunos.uminho.pt>

category:             Game
abi:                  inplace
exposed:              True
exposed-modules:      LI12425 Tarefa1 Tarefa2 Tarefa3
import-dirs:
    /Users/guilherme/Code/1ano/li1/tower-defense/dist-newstyle/build/aarch64-osx/ghc-9.2.8/immutable-towers-0.0.0.0/build

library-dirs:
    /Users/guilherme/Code/1ano/li1/tower-defense/dist-newstyle/build/aarch64-osx/ghc-9.2.8/immutable-towers-0.0.0.0/build

dynamic-library-dirs:
    /Users/guilherme/Code/1ano/li1/tower-defense/dist-newstyle/build/aarch64-osx/ghc-9.2.8/immutable-towers-0.0.0.0/build

data-dir:             /Users/guilherme/Code/1ano/li1/tower-defense/.
hs-libraries:         HSimmutable-towers-0.0.0.0-inplace
depends:              base-4.16.4.0 rndm-1.2.1.2-7be68b6b
haddock-interfaces:
    /Users/guilherme/Code/1ano/li1/tower-defense/dist-newstyle/build/aarch64-osx/ghc-9.2.8/immutable-towers-0.0.0.0/doc/html/immutable-towers/immutable-towers.haddock

haddock-html:
    /Users/guilherme/Code/1ano/li1/tower-defense/dist-newstyle/build/aarch64-osx/ghc-9.2.8/immutable-towers-0.0.0.0/doc/html/immutable-towers
